package pt.isel.service.auth.model

/**
 *  `Tokens`
 *
 * Represents a JWT pair generated by the application and returned on a successful login.
 *
 * @property [accessToken] The generated access token.
 * @property [refreshToken] The generated refresh token.
 * */
data class TokenPair(
    val accessToken: String,
    val refreshToken: String
)